### ISSUE TITLE
Перестал работать модуль

### ISSUE THREAD

**Issue by ghost** [maksimyurkov/webtutor-push-notifications#2]
Здравствуйте, подскажите в чем может быть проблема и куда копать?
На странице "node_modules/@maksimyurkov/webtutor-push-notifications/dist/index.html" проверку проходит, но в устройствах пусто.
Ошибки которые удалось отловить:
![image](https://user-images.githubusercontent.com/80817040/111440110-13bbbb80-8717-11eb-9ebc-16f83ed3b25f.png)
![image](https://user-images.githubusercontent.com/80817040/111440297-41a10000-8717-11eb-95e0-1d9fe499f831.png)
![image](https://user-images.githubusercontent.com/80817040/111440340-4a91d180-8717-11eb-8f9a-7f394b87e356.png)
![image](https://user-images.githubusercontent.com/80817040/111440370-51204900-8717-11eb-8a56-e3a24e5e1af7.png)

Очень прошу помощи

**Comment by maksimyurkov** [comment]
Добрый день!

Думаю проблема на клиентской части и скорее всего связана с какими-нибудь изменениями в firebase.

На моей стороне клиентская часть лежит тут =>
https://github.com/maksimyurkov/webtutor-push-notifications/blob/master/webtutor/components/templates/init/init.js
+ используются библиотеки Firebase (указаны в package.json) 

![image](https://user-images.githubusercontent.com/17424327/111861416-232d4580-895f-11eb-9157-b63c182346a7.png)

Я бы рекомендовал, все с нуля переустановить и попробовать различные устройства и браузеры для приема уведомлений.

Если не поможет, то в package.json можно попробовать поменять версию firebase, все пересобрать (npm run build) и попробовать снова.

Если и это не поможет, то думаю надо искать решение по ошибке из первого скрина, бывают случаи, когда они что-то у себя меняют кардинально и что-то перестает работать, но они об этом обычно предупреждают.
